# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170511_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
