# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_choice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
